### ISSUE TITLE
莫队

### ISSUE THREAD

**Issue by sshockwave** [syniox/Online_Judge_solutions#26]
- [x] `XSY1651` 裸
- [x] `BZOJ2120` 带修改

**Comment by syniox** [comment]
树上莫队做法：
对树进行dfs，进入时加入一次，退出时加入一次队列。
现在对于一个询问[x,y]，由x和y分别构成的区间一定是包含或者相离的。
假如相离的话提取出区间后手动维护一下lca。

**Comment by sshockwave** [comment]
参考资料：https://blog.csdn.net/xianhaoming/article/details/52201761
